// Campaign map model — the Neon City node-graph. Adapted from the old
// adventure map model, with defended "system" nodes instead of
// obstacle/rival/treasure events. Map JSONs are generated by
// scripts/generate-city.mjs and committed under public/assets/maps/.

import type { CharacterId } from '../game/characters';

export type NodeDifficulty = 'easy' | 'medium' | 'hard';

export type CampaignNodeKind = 'entry' | 'junction' | 'system';

export interface CampaignNode {
  id: string;
  /** entry = spawn point; junction = free walkable connector; system = defended battle node. */
  kind: CampaignNodeKind;
  /** Critical systems gate map completion. Only ever true on 'system' nodes. */
  critical: boolean;
  /** Characters guarding this node (1-6 on system nodes, empty otherwise). */
  defenders: CharacterId[];
  /** Explicit AI difficulty for the battle at this node. */
  difficulty: NodeDifficulty;
  /** Horizontal position as fraction of map width (0..1). */
  x: number;
  /** Vertical position as fraction of total map height (0 = top, 1 = entry). */
  y: number;
  /** Visual zone for styling (biome analog). */
  district: string;
  connections: string[];
}

export type CampaignMapId = 'map_1' | 'map_2' | 'map_3';

export const CAMPAIGN_MAP_IDS: CampaignMapId[] = ['map_1', 'map_2', 'map_3'];

export interface CampaignMapJson {
  id: CampaignMapId;
  name: string;
  /** Map height as a multiple of the viewport height (bigger maps scroll longer). */
  heightFactor: number;
  entryNodeId: string;
  nodes: CampaignNode[];
}

export class CampaignMapDef {
  readonly id: CampaignMapId;
  readonly name: string;
  readonly heightFactor: number;
  readonly entryNodeId: string;
  readonly nodes: CampaignNode[];
  private readonly byId: Map<string, CampaignNode>;

  constructor(json: CampaignMapJson) {
    this.id = json.id;
    this.name = json.name;
    this.heightFactor = json.heightFactor;
    this.entryNodeId = json.entryNodeId;
    this.nodes = json.nodes.map((n) => ({
      ...n,
      defenders: n.defenders ?? [],
      connections: n.connections ?? [],
    }));
    this.byId = new Map(this.nodes.map((n) => [n.id, n]));
  }

  nodeById(id: string): CampaignNode {
    const node = this.byId.get(id);
    if (!node) throw new Error(`Unknown campaign node: ${id}`);
    return node;
  }

  neighborsOf(id: string): string[] {
    return this.nodeById(id).connections;
  }

  /** Deduplicated undirected edges as [a, b] with a < b. */
  get edges(): Array<[string, string]> {
    const seen = new Set<string>();
    const result: Array<[string, string]> = [];
    for (const node of this.nodes) {
      for (const other of node.connections) {
        const key = node.id < other ? `${node.id}|${other}` : `${other}|${node.id}`;
        if (!seen.has(key)) {
          seen.add(key);
          result.push(node.id < other ? [node.id, other] : [other, node.id]);
        }
      }
    }
    return result;
  }

  get systemNodes(): CampaignNode[] {
    return this.nodes.filter((n) => n.kind === 'system');
  }

  get criticalNodes(): CampaignNode[] {
    return this.nodes.filter((n) => n.critical);
  }
}

export async function loadCampaignMap(
  baseUrl: string,
  mapId: CampaignMapId,
): Promise<CampaignMapDef> {
  const res = await fetch(`${baseUrl}assets/maps/${mapId}.json`);
  if (!res.ok) throw new Error(`Failed to load campaign map ${mapId}: ${res.status}`);
  const json = (await res.json()) as CampaignMapJson;
  return new CampaignMapDef(json);
}

export async function loadAllCampaignMaps(
  baseUrl: string,
): Promise<Record<CampaignMapId, CampaignMapDef>> {
  const [m1, m2, m3] = await Promise.all(CAMPAIGN_MAP_IDS.map((id) => loadCampaignMap(baseUrl, id)));
  return { map_1: m1, map_2: m2, map_3: m3 };
}
