import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import prettier from 'eslint-config-prettier';

export default tseslint.config(
  // android/, ios/ and dist-mobile/ are generated by Capacitor (`npx cap add`).
  { ignores: ['dist', 'dev-dist', 'dist-mobile', 'node_modules', 'android', 'ios'] },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['src/**/*.{ts,tsx}'],
    plugins: { 'react-hooks': reactHooks },
    rules: {
      ...reactHooks.configs.recommended.rules,
      // App/AdventureMap intentionally read ref-backed caches during render,
      // paired with a counter state that forces the re-render.
      'react-hooks/refs': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
    },
  },
  {
    files: ['scripts/**/*.{mjs,ts}'],
    languageOptions: {
      globals: { console: 'readonly', process: 'readonly', Buffer: 'readonly' },
    },
  },
  prettier,
);
